# Generated by Django 5.2.4 on 2025-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default=1, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
