# Generated by Django 5.2.4 on 2025-07-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0003_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=225),
        ),
    ]
