# Generated by Django 5.2.4 on 2025-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kudosuser",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kudosuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
