# Generated by Django 5.2.4 on 2025-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_kudosuser_department_kudosuser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kudosuser",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="kudosuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
