# Generated by Django 5.2.4 on 2025-07-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_kudosuser_profile_picture_kudosuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kudosuser",
            name="is_admin",
        ),
    ]
