# Generated by Django 5.2.4 on 2025-07-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_is_admin_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kudosuser",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
