# Generated by Django 5.2.4 on 2025-07-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recognition",
            old_name="tags",
            new_name="skills",
        ),
    ]
