# Generated by Django 5.2.4 on 2025-07-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_tags_recognition_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recognition",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
    ]
