# Generated by Django 5.2.4 on 2025-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_skills"),
        ("dashboard", "0003_remove_recognition_skills_delete_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognition",
            name="skills",
            field=models.ManyToManyField(
                related_name="recognitions", to="admin_dashboard.skills"
            ),
        ),
    ]
