# Generated by Django 5.2.4 on 2025-07-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_recognition_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recognition",
            name="category",
        ),
    ]
