# Generated by Django 5.2.4 on 2025-07-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_skills"),
        ("dashboard", "0005_remove_recognition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognition",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recognitions_category",
                to="admin_dashboard.category",
            ),
            preserve_default=False,
        ),
    ]
