# Generated by Django 5.2.4 on 2025-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_recognition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognition",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("REJECTED", "REJECTED"),
                    ("APPROVED", "APPROVED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
